services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sypets\SypetsXclassDi\:
    resource: '../Classes/*'

  # extra definitions for XCLASS's classes where the new class adds dependencies in constructor
  # https://www.derhansen.de/2021/06/how-to-use-constructor-injection-with-typo3-xclass.html
  # https://github.com/derhansen/xclass_di/issues/1

  # (1) alternative to make XCLASS's class with DI contructor (of core class without constructor) work
  #  # !!! does not work

  #TYPO3\CMS\Backend\Preview\StandardContentPreviewRenderer: '@Sypets\SypetsXclassDi\Backend\PreviewRenderer\Hook\StandardContentPreviewRenderer'


  # (2) alternative to make XCLASS's class with DI contructor (of core class without constructor) work
  #  # !!! does not work

  #TYPO3\CMS\Backend\Preview\StandardContentPreviewRenderer: '@Sypets\SypetsXclassDi\Backend\PreviewRenderer\Hook\StandardContentPreviewRenderer'

  #Sypets\SypetsXclassDi\Backend\PreviewRenderer\Hook\StandardContentPreviewRenderer:
  #  public: true
  #  autowire: false
  #  arguments:
  #    $assetCollector: '@TYPO3\CMS\Core\Page\AssetCollector'

  # (3) alternative to make XCLASS's class with DI contructor (of core class without constructor) work
  # !!! does not work

  sypets.sypetsxclssdi.xlass_preview:
    class: Sypets\SypetsXclassDi\Backend\PreviewRenderer\Hook\StandardContentPreviewRenderer

  Sypets\SypetsXclassDi\Backend\PreviewRenderer\Hook\StandardContentPreviewRenderer:
    public: true

  typo3.cms.backend.preview.standardcontentpreviewrenderer: '@sypets.sypetsxclssdi.xlass_preview'



